### ISSUE TITLE
[Feature Request]: Support for custom world gen

### ISSUE THREAD

**Issue by iijj22gg** [FamroFexl/Circumnavigate#33]
### Suggestion

Suggestion to add support for custom world gen, for mods such as Big Globe and BetterX

**Comment by FamroFexl** [comment]
It does look like those mods use some form of custom perlin noise, making them incompatible with my future vanilla changes. This may mean they will require support from their developers. However, worldgen datapacks should be supported by default.

Although this is all theoretical, since I've just started testing my wrapped world generation, and it looks a long way off. (#30)
