### ISSUE TITLE
[Bug]: View distance linked to size of world 

### ISSUE THREAD

**Issue by KuraLychee** [FamroFexl/Circumnavigate#7]
### Describe the Bug

View distance unable to be increased on smaller worlds, for instance, a world with a -4, 4, -4, 4 boundary will leave you unable to see past a few chunks before seeing fog, I'm unaware if this is intentional or not, if so, a toggle or a config might be beneficial

### Mod version(s) affected

Both 0.1 and 0.2

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

### Other mods used

Fabulously Optimized 5.10.3 (An optimization modpack)

### To Reproduce (If applicable)

1. Go into world creation
2. Select wrapped world option
3. Set border to something small (Like -8, 8, -8, 8, or -4, 4, -4, 4)
4. Load world

**Comment by FamroFexl** [comment]
This is intentional. If the view distance were not limited to world size, the client would stop loading incoming chunks and glitch out past the last loaded chunk. The fog was also modified to keep the player from seeing the obvious edges of the world. While this modified fog rendering isn't necessary, it keeps vanilla parity.

Chunks can only be loaded if they aren't loaded, meaning they have to be unloaded before they can be loaded again  ([see comment](https://www.reddit.com/r/feedthebeast/comments/1fduvvb/comment/lmj7jg3/)). If I were somehow able to make them load twice, this would likely remove vanilla client compatibility.
